### PR TITLE
Fix: logger adapter does not insert extra

### PR DESCRIPTION
**Pull request by mcoolive**
- process method should take the object passed as extra to the
constructor and adds it to kwargs using key ‘extra’.

### CODE REVIEW

**Comment by jobec** [comment]
Do you have a piece of example code for this?

I’m not entirely getting what the bug is.

**Comment by mcoolive** [comment]
Hi jobec,

First thank you for the lib that do what I need.

Here, more context about my issue. In our compagny, we use rsyslog to centralise logs and for "_historical_ reasons", the message (so after the structured data) can be prefixed by a list of 'labels' that will be indexed. So in my Python code it seams convenient to configure the logger as follow:

> rootLogger = logging.getLogger()
> syslogHandler = Rfc5424SysLogHandler(facility='local5', appname=appname)
> extra['labels'] = ' '.join(['lbl1', 'lbl2', 'lbl3')])
> syslogFormatter = logging.Formatter(fmt='[%(labels)s] %(message)s')
> syslogHandler.setFormatter(syslogFormatter)
> rootLogger.addHandler(syslogHandler)
> 
> # The module logger wrapped to provide labels to the formatter and extra levels
> logger = logging.getLogger(__name__)
> logger = Rfc5424SysLogAdapter(logger, extra, enable_extra_levels=True)

But the logging failed because the 'labels' is unknown by the formatter. My understanding is that Rfc5424SysLogAdapter manage the 'extra' provided in kwargs of each log statement, but do nothing with the extra given to Rfc5424SysLogAdapter.__init__
My program works if I replace Rfc5424SysLogAdapter by logging.LoggerAdapter (but then I don't have extra_level...)

**Comment by mcoolive** [comment]
Note. I first consider to add a call to super(Rfc5424SysLogAdapter, self).process(self, msg, kwargs), but the implementation of logging.LoggerAdapter simply replace kwargs["extra"] by self.extra (so the extra provided by the log statement are ignored...)

My PR suggests to merge extra from the log statements with the one given at adapter initialisation.

**Comment by jobec** [comment]
Released v1.1.1

**Pull request merged**
