### PR TITLE
Added a custom logger to easily pass msgid and structured_data as parameters

### PR DESCRIPTION
**Pull request by mhbrown**
Added a custom logger to easily pass `msgid` and `structured_data` as parameters

@jobec FYI I sent you an email asking about the ideal way to pass in `msgid` and `structured_data`. I added the custom logger here since @TheMikeGood and I would likely have to do it anyways, and I thought it can probably be reused by you or others. Please feel free to approve/reject.

### CODE REVIEW

**Comment by jobec** [comment]
Logging structured data goes like this:
```python
import logging
from rfc5424logging import Rfc5424SysLogHandler

logger = logging.getLogger('test')
logger.addHandler(Rfc5424SysLogHandler(address=('127.0.0.1', 514), enterprise_id=32473))

extra = {
    'structured_data': {
        'my_structured_data_ID': {'my_key': "some value"}
    }
}

logger.error("I'm a message with structured data", extra=extra)
```

Writing and using a extra class for it feels a bit like overkill.

Maybe some alternatives like this ?:
https://docs.python.org/3/howto/logging-cookbook.html#using-loggeradapters-to-impart-contextual-information
Or a helper function for building the extra parameter?

**Comment by mhbrown** [comment]
@jobec Thanks for the feedback, and the `structured_data` example! I hadn't used the `logging.LoggerAdapter` class before. I just did some testing with the below custom adapter I wrote and it seems to work. Please let me know if you think it would be good to have in this repo.

```
from logging import LoggerAdapter

from handler import NILVALUE


class Rfc5424SysLoggerAdapter(LoggerAdapter):
    def __init__(self, logger, msgid=NILVALUE, structured_data=None):
        if structured_data is None:
            structured_data = {}
        extra = {
            'structured_data': structured_data,
            'msgid': msgid
        }
        super(Rfc5424SysLoggerAdapter, self).__init__(logger, extra)
```

**Comment by jobec** [comment]
After searching in a lot of directions, this looks like the most efficient way at the moment

An LoggerAdapter subclass
```python 
import logging


class Rfc5424SysLogAdapter(logging.LoggerAdapter):
    def __init__(self, logger, extra=None):
        super(Rfc5424SysLogAdapter, self).__init__(logger, extra or {})

    def process(self, msg, kwargs):
        return msg, kwargs

    def log(self, level, msg, *args, **kwargs):
        msgid = kwargs.pop('msgid', None)
        structured_data = kwargs.pop('structured_data', None)

        if 'extra' not in kwargs:
            kwargs['extra'] = {}

        if msgid:
            kwargs['extra']['msgid'] = msgid
        if structured_data:
            kwargs['extra']['structured_data'] = structured_data

        super(Rfc5424SysLogAdapter, self).log(level, msg, *args, **kwargs)
```
Used like this:
```python
import logging
from rfc5424logging import Rfc5424SysLogHandler
from rfc5424logging.adapter import Rfc5424SysLogAdapter

logger = logging.getLogger('test.test')
logger.addHandler(Rfc5424SysLogHandler(address=('127.0.0.1', 514), enterprise_id=32473))

logger = Rfc5424SysLogAdapter(logger)

logger.error("test1", structured_data={'sd_id': {'my_key': "some_value"}}, msgid="msg_id")
```
Still I need to investigate the implications when also logging to console etc. It's not uncommon to log to console and syslog at the same time.

**Comment by berkeleydiego** [comment]
good stuff, thanks @mhbrown

**Comment by jobec** [comment]
I've pushed a first attempt to such adapter class. See commit 78d5785fcb14aef77df507880e7d748dc9c8debb

**Comment by mhbrown** [comment]
Awesome, thanks @jobec! I'll test it out and let you know if there's any issues. 👍

**Comment by mhbrown** [comment]
Closing since `adapter.py` is being added instead

**Pull request closed without merging**
