### PR TITLE
Pip fix + Python 2.x super compat

### PR DESCRIPTION
**Pull request by TheMikeGood**

### CODE REVIEW

**Comment by jobec** [comment]
I actually did not test this package against python 2. (My initial scope was also just python 3 due to the strings vs. bytes mess between python 2 and 3).

If it works just like, all the better. But that also means updating setup.py to indicate python 2.7 support.

I'll do some tests and come back on this.

**Comment by TheMikeGood** [comment]
Cool. The super() issue was the only compat issue I noticed on my end. Feel free to let me know if there's anything else I can do to contribute.

**Comment by jobec** [comment]
Well I'll be damned :-) It indeed does work in 2.7...

**Comment by TheMikeGood** [comment]
@jobec - Working with @mhbrown , found another issue on his machine. PR pending. ;)

**Comment by jobec** [comment]
This seems to break things in python 3...

**Comment by jobec** [comment]
And it also give this error in python 2:

`TypeError: super() takes at most 2 arguments (3 given)`

**Comment by TheMikeGood** [comment]
Aye. @mhbrown is forking for a solution, I believe.

**Comment by jobec** [comment]
`super(Rfc5424SysLogHandler).__init__(address, facility, socktype)`
->
`super(Rfc5424SysLogHandler, self).__init__(address, facility, socktype)`

**Comment by jobec** [comment]
This package certainly needs CI build checking 😊

**Pull request merged**
